---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: pageviews
  namespace: vault-tests
spec:
  replicas: 3
  partitionCount: 1
  kafkaClusterRef:
    name: kafka
    namespace: vault-tests
